#!/bin/sh

# nitrogen --restore
xrdb -load ~/.Xresources
xset r rate 200 60
setxkbmap us

picom --experimental-backends &
gromit-mpx &
killall sxhkd; sxhkd $HOME/code/dots/keys/sxhkdrc &

$HOME/.local/bin/ticktack stop
killall ticktack
$HOME/.local/bin/ticktack start -m 30 &

if [ "$(cat /sys/class/dmi/id/chassis_type)" -eq 3 ]; then
        exit
else
        kmonad $HOME/code/dots/keys/kmonad.kbd &
fi

