#!/bin/sh

function autostart() {
    pgrep -u $USER -x $1 > /dev/null || ($1)
} 

nitrogen --restore
xrdb -load ~/.config/X/Xresources

# overpowered capslock
setxkbmap -option caps:super
xcape -e 'Super_L=Escape'

# all the daemons and background stuff 
emacs --daemon &
killall sxhkd; sxhkd &
mpd &
greenclip daemon &
picom &
autostart aw-qt &

