#!/bin/sh

nitrogen --restore
xrdb -load ~/.Xresources
xset r rate 200 60

# all the daemons and background stuff 
# emacs --daemon &
# mpd &
# killall mpd-mpris; mpd-mpris &
greenclip daemon &
picom &
killall sxhkd; sxhkd $HOME/code/dots/keys/sxhkdrc &

$HOME/.local/bin/ticktack stop
killall ticktack
$HOME/.local/bin/ticktack start -m 30 &

kmonad $HOME/code/dots/keys/kmonad.kbd &

