#!/bin/sh
# provides a nice rofi menu to chose a new xrdb colorscheme and call the update script

BASEDIR=$(dirname $0)
PATHXPRISON="$BASEDIR/../xprison"

# get input 
[ "$1" == "" ] && CHOICE=$(ls "$PATHXPRISON/colors" | rofi -dmenu -i -p "Choose a colorscheme: " | tr -d '\n') || CHOICE=$1

# check input
[ "$CHOICE" == "" ] && exit
[[ -e "$PATHXPRISON/colors/$CHOICE" ]] || exit

# updaet the Xresource file and the database
cp "$PATHXPRISON/colors/$CHOICE" "$HOME/.Xresources"
cat "$PATHXPRISON/base.xres" >> "$HOME/.Xresources"
xrdb -load "$HOME/.Xresources"

# update all the config files and push them to their place
$BASEDIR/dots-update

# update emacs (if run as a server)
emacsclient -e "(load-theme 'xresources)" 
emacsclient -e '(load-file "~/.emacs.d/visuals/sumibi-modeline.el")'

# update awesomewm widgets (currently only through reloading the wm)
# awesome-client "awesome.restart()" 

# reload gtk (thanks to phischs reloader)
cd $HOME/code/dots/xprison/res/gtk
make
sudo make install
npm run reload_gtk_theme

echo "Success! Colorscheme set to $CHOICE"
