#!/bin/sh
# comfy dmenu for taking screenshots

SAVE_PATH="$HOME/pics/screenshots/$(date +%y-%m-%d_%H-%M-%S).png"

[ "$1" == "" ] && SELECTION=$(echo -e "all\nby selection\nby active window" | rofi -dmenu -i -p "What area? " | tr -d '\n') || SELECTION="$1"
[ "$SELECTION" == "" ] && exit

[ "$2" == "" ] && SAVE=$(echo -e "save\ndon't save" | rofi -dmenu -i -p "Save it?" | tr -d '\n') || SAVE="$2"
[ "$SAVE" == "" ] && exit

[ "$SAVE" == "save" ] && TEE_CMD="tee $SAVE_PATH" || TEE_CMD="tee"

case $SELECTION in 
    "all")
        sleep 1
        maim | $TEE_CMD | xclip -selection clipboard -t image/png
        ;;
    "by selection")     
        maim -s -u | $TEE_CMD | xclip -selection clipboard -t image/png 
        ;;
    "by active window") 
        sleep 1
        maim -i $(xdotool getactivewindow) | $TEE_CMD | xclip -selection clipboard -t image/png 
        ;;
    "")                 
        exit 
        ;;
esac

[ "$SAVE" == "save" ] && notify-send "[!] Screenshot taken" "~/pics/screenshots/$TIMESTAMP" --icon="$SAVE_PATH"

