#!/bin/sh
# cpmfy dmenu for exiting, rebooting and so on

action=$(echo -e "shutdown\nreboot\nsuspend\nquit awesome\nrestart awesome" | rofi -dmenu -i -p "What do you want to do? ")
[ "$action" == "" ] && exit

affirm=`echo -e "no\nyes" | rofi -dmenu -i -p "You sure?"`
[ "$affirm" != "yes" ] && exit

echo "$action"

case $action in
    "shutdown")
        systemctl poweroff
        ;;
    "reboot")
        systemctl reboot
        ;;
    "suspend")
        systemctl suspend
        ;;
    "quit awesome")
        awesome-client "awesome.quit()"
        ;;
    "restart awesome")
        awesome-client "awesome.restart()"
        ;;
esac

exit 0

