#!/bin/sh
# pulls and pushes the actual config from wherever it lies on the system or to wherever it should be

BASEDIR=$(dirname $0)

# emacs config 
cp -f $HOME/.config/emacs/config.org $BASEDIR/../emacs/config.org
cp -f $HOME/.config/emacs/init.el $BASEDIR/../emacs/init.el
cp -f $HOME/.config/emacs/doom-mine-theme.el $BASEDIR/../emacs/doom-mine-theme.el

rsync -rH $HOME/.config/awesome $BASEDIR/..
